- src/renderer/components/SystemPage/RightPanelServer.vue
- src/renderer/components/SystemPage/RightPanelServer/CreateDepartments.vue
- src/renderer/components/SystemPage/RightPanelServer/CreateOrgs.vue
- src/renderer/components/SystemPage/RightPanelServer/GetOrgs.vue
- src/renderer/components/SystemPage/RightPanelServer/GetPersons.vue
- src/renderer/components/SystemPage/RightPanelServer/GetUsers.vue
- src/renderer/store/modules/System.js
- src/renderer/utils/Server.js
> 拆分RightPanelServer文件；

- src/renderer/components/StatPage/RightBar.vue
- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/components/SystemPage/DrgBar.vue
- src/renderer/components/SystemPage/LeftPanel.vue
- src/renderer/components/SystemPage/RightPanelDrg.vue
- src/renderer/store/modules/Stat.js
- src/renderer/store/modules/System.js
> 调试本地和服务器端调用分组器

- src/renderer/components/SystemPage/RightPanelStat.vue
- src/renderer/components/SystemPage/RightPanelStat/Dimension.vue
- src/renderer/components/SystemPage/StatBar.vue
- src/renderer/store/modules/Stat.js
- src/renderer/store/modules/System.js
> 添加分组计算服务器数据获取

- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/components/StatPage/RightBar.vue
- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/components/SystemPage/RightPanelServer.vue
- src/renderer/store/modules/Library.js
- src/renderer/store/modules/Stat.js
> 添加stat搜索功能

- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/components/SystemPage/RightPanelServer.vue
- src/renderer/components/SystemPage/RightPanelServer/GetPersons.vue
- src/renderer/components/SystemPage/ServerBar.vue
- src/renderer/store/modules/Stat.js
- src/renderer/store/modules/System.js
- src/renderer/utils/Server.js
- src/renderer/utils/StatServerFile.js
> 添加stat远程分页

- src/renderer/components/HomePage/NavBar.vue
- src/renderer/components/StatPage/RightBar.vue
- src/renderer/components/SystemPage/RightPanelServer/CreateDepartments.vue
- src/renderer/components/SystemPage/RightPanelServer/CreateOrgs.vue
- src/renderer/components/SystemPage/RightPanelServer/GetOrgs.vue
- src/renderer/components/SystemPage/RightPanelServer/GetPersons.vue
- src/renderer/components/SystemPage/ServerBar.vue
- src/renderer/store/modules/Library.js
- src/renderer/store/modules/System.js
- src/renderer/utils/Server.js
修改系统设置机构分页
增加 就够科室分页功能
调整system 页面样式
> 修改字典库维度选择查询错误

- src/renderer/components/SystemPage/DrgBar.vue
- src/renderer/components/SystemPage/LoadBar.vue
- src/renderer/components/SystemPage/RightPanelDrg.vue
- src/renderer/components/SystemPage/ServerBar.vue
- src/renderer/components/SystemPage/StatBar.vue
- src/renderer/store/modules/System.js
> 添加system分页提醒

- src/renderer/components/EditPage/LeftBar.vue
- src/renderer/components/SystemPage/DrgBar.vue
- src/renderer/components/SystemPage/LeftPanel.vue
- src/renderer/components/SystemPage/RightPanelDrg.vue
- src/renderer/components/SystemPage/RightPanelServer.vue
- src/renderer/components/SystemPage/RightPanelServer/GetOrgs.vue
- src/renderer/components/SystemPage/RightPanelStat.vue
- src/renderer/components/SystemPage/ServerBar.vue
- src/renderer/components/SystemPage/StatBar.vue
- src/renderer/store/modules/System.js
> 添加system注释

- src/renderer/components/HomePage/NavBar.vue
- src/renderer/components/SystemPage/RightPanelLoad.vue
- src/renderer/components/SystemPage/RightPanelServer.vue
- src/renderer/components/SystemPage/StatBar.vue
- src/renderer/utils/LoadFile.js
修改系统服务本地默认界面显示
修改系统服务远程服务器设置默认显示界面
> 修改区块链默认显示界面

- src/renderer/components/SystemPage/LeftPanel.vue
- src/renderer/components/SystemPage/LoadBar.vue
- src/renderer/components/SystemPage/RightPanelServer/CreateDepartments.vue
- src/renderer/utils/Server.js
> 修改本地文件上传校验功能

- src/renderer/components/EditPage/LeftBar.vue
- src/renderer/components/EditPage/LeftPanelTable.vue
- src/renderer/components/EditPage/RightBar.vue
- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/components/SystemPage/LoadBar.vue
- src/renderer/store/modules/Library.js
- src/renderer/utils/LibraryServerFile.js
> 修改edit翻页bug

- src/renderer/components/SystemPage/DrgBar.vue
- src/renderer/components/SystemPage/LoadBar.vue
- src/renderer/components/SystemPage/RightPanelLoad.vue
- src/renderer/store/modules/System.js
> 调整服务分组分页bug

- src/renderer/components/BlockChain/RightPanelBlock.vue
- src/renderer/components/LibraryPage/LeftPanelFile.vue
- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/store/modules/System.js
- src/renderer/utils/BlockBlock.js
- src/renderer/utils/Server.js
> 修复block显示bug

- src/renderer/store/modules/Library.js
- src/renderer/utils/LibraryServerFile.js
> 修复字典库模糊查询bug

- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/store/modules/Library.js
- test/e2e/specs/Library.spec.js
- test/e2e/specs/LibraryBlockFile.spec.js
> 修改 library 维度下拉 动态按钮

- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/store/modules/Library.js
- src/renderer/utils/ChartBar.js
- src/renderer/utils/LibraryServerFile.js
- src/renderer/utils/SaveFile.js
> 增加字典库cdh下载功能

- src/renderer/components/StatPage/RightBar.vue
- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/components/StatPage/RightPanelCustom.vue
- src/renderer/utils/Server.js
> 修改自定义查询页面样式

- src/renderer/components/LibraryPage/LeftPanelDimension.vue
- src/renderer/components/LibraryPage/LeftPanelFile.vue
- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/components/LibraryPage/RightPanel.vue
- src/renderer/utils/LibraryServerFile.js
- src/renderer/utils/SaveFile.js
> 修改字典库翻页bug

- src/renderer/components/LibraryPage/RightPanel.vue
- src/renderer/components/StatPage/RightPanel.vue
- src/renderer/utils/EditServerFile.js
- test/e2e/specs/LibraryRemoteFile.spec.js
- test/e2e/specs/StatRemoteFile.spec.js
> 修改npm run test

- src/renderer/components/LibraryPage/RightBar.vue
- src/renderer/components/LibraryPage/RightPanel.vue
- src/renderer/store/modules/Library.js
- src/renderer/utils/LibraryServerFile.js
- src/renderer/utils/SaveFile.js
- test/e2e/index.js
- test/e2e/specs/Library.spec.js
- test/e2e/specs/LibraryBlockFile.spec.js
- test/e2e/specs/LibraryLocalFile.spec.js
- test/e2e/specs/LibraryRemoteFile.spec.js
> 重构library代码
